### ISSUE TITLE
Stable document is not deployed

### ISSUE THREAD

**Issue by hyrodium** [JuliaTesting/ReferenceTests.jl#104]
https://juliatesting.github.io/ReferenceTests.jl/v0.9/ returns 404, but https://juliatesting.github.io/ReferenceTests.jl/dev/ is deployed.

This is because the setting of `DOCUMENTER_KEY` is not correct.
See more information in https://juliadocs.github.io/Documenter.jl/dev/man/hosting/#GitHub-Actions.

![image](https://user-images.githubusercontent.com/7488140/146172021-54e693d2-c274-47cb-b8a2-b5b11be1d2b4.png)

**Comment by johnnychen94** [comment]
Thanks for the notification! In f59a639bd2f2228bffaf214923407c8a42993dbe I've added ssh key for both CompatHelper and TagBot, hope we can successfully trigger it in the next release.

In the meantime, I've manually recreated a tag `v0.9.9+doc1` to trigger the release build for documentation.

**Comment by johnnychen94** [comment]
For unknown reasons, Documenter refuses to update `stable` with `v0.9.9+doc1` so I manually create a not-yet-existed version `v0.9.10` tag and then immediately removed it. Just to link stable version to v0.9.

I also tried to manually modify `gh-pages` branch and then GitHub refuses to build pages for my manual commit 😢

**Comment by hyrodium** [comment]
>For unknown reasons, Documenter refuses to update `stable` with `v0.9.9+doc1`

That was because we have `[compat]` table in [`docs/Project.toml`](https://github.com/JuliaTesting/ReferenceTests.jl/blob/master/docs/Project.toml#L6) and the specified version was old.

The version with meta (like `v0.9.9+doc1`) seems available since Documenter v0.25 because the "Fixing broken release deployments" section is not documented in v0.2 4. https://juliadocs.github.io/Documenter.jl/v0.24/
