### ISSUE TITLE
Is the package working fine in Julia v1.7?

### ISSUE THREAD

**Issue by juliohm** [JuliaTesting/ReferenceTests.jl#108]
I am trying to update all my tests to Julia v1.7 and some of them are stuck on @test_reference calls with malloc: corrupted top size issues even when I erase the data in the test folder.

Could you please confirm that this package supports Julia v1.7 already?

**Comment by juliohm** [comment]
This is the package for which the tests are stuck on Julia v1.7: https://github.com/JuliaEarth/GeoSimulation.jl/actions/runs/1790064608

Apparently the issue is only happening on Linux.

**Comment by juliohm** [comment]
Any recent change to the codebase that could potentially break the behavior of visual tests with Plots.jl expressions? I noticed that my tests are stuck on Julia v1.6 as well on the GitHub CI.

**Comment by johnnychen94** [comment]
It's hard to diagnose without an MWE. Maybe https://github.com/JuliaPlots/Plots.jl/issues/4091 is relavent.

**Comment by juliohm** [comment]
Thank you @johnnychen94 , probably another Plots.jl bug.

I think I am done with Plots.jl. I will try to migrate all my visual tests to Makie.jl.

Is ReferenceTests.jl integrated with CairoMakie.jl for example? Can I just plug a Makie.plot(...) as my expression? Will read the docs carefully when I find some time.

**Comment by t-bltg** [comment]
It would be useful if we had a plain backtrace. I'm only on a laptop now and cannot build julia with debugging symbols and run under a debugger. I think it's the same bug / hang as in https://github.com/JuliaPlots/Plots.jl/issues/4091, on `windows` and `linux` but not `macos`.

**Comment by t-bltg** [comment]
> probably another Plots.jl bug.

No.

Can be closed, fixed by https://github.com/JuliaIO/PNGFiles.jl/pull/54.

**Comment by johnnychen94** [comment]
Thanks for tracking this down!
