### ISSUE TITLE
porting to JuliaTesting

### ISSUE THREAD

**Issue by johnnychen94** [JuliaTesting/ReferenceTests.jl#54]
This idea is originally proposed by @oxinabox in slack

**Comment by Evizero** [comment]
I am happy to press the transfer button at any time really. Main reason I didn't do that yet because I am not sure if it can break anything. However, I am not up to speed about any other steps that need to be taken and would appreciate someone else performing them if possible.

**Comment by johnnychen94** [comment]
The old URL is still valid even if it's transferred to a new place. We've transferred ImageContrastAdjustment to Images recently, and it's:

1. hit the transfer button
2. update CI settings

Ref: https://github.com/JuliaImages/Images.jl/pull/855#issuecomment-569912692

**Comment by oxinabox** [comment]
Update the URL in the registry too for completeness.
(Even though it will redirect until something else (like a fork) is put at old URL)
Full instructions:
https://github.com/JuliaRegistries/General#how-do-i-transfer-a-package-to-an-organization-or-another-user

**Comment by johnnychen94** [comment]
I'll fix the CI later today/tomorrow.

**Comment by Evizero** [comment]
I pushed the button. welcome to your new home, old friend.

Thank you two! This is surely the right place. It was your contributions that turned it into a proper package after all

**Comment by johnnychen94** [comment]
CI fixed in #56

**Comment by kimikage** [comment]
a remembrance :smile:
https://github.com/JuliaTesting/ReferenceTests.jl/blame/30aa43f/README.md#L88

**Comment by johnnychen94** [comment]
Yes, the documentation definitely needs an update, I plan to do that after #61

**Comment by kimikage** [comment]
It's an issue with the broken link, not the documentation.
