### ISSUE TITLE
Error in MacOS only

### ISSUE THREAD

**Issue by juliohm** [JuliaTesting/ReferenceTests.jl#73]
The test we have added in ImageInpainting.jl with a *.txt file fails on MacOS for some unknown reason:

https://github.com/JuliaImages/ImageInpainting.jl/runs/1858622127?check_suite_focus=true#step:6:60

Any idea of what can be causing the failure? This is a simple diagonal matrix saved as text file.

**Comment by oxinabox** [comment]
that is super bizare

**Comment by johnnychen94** [comment]
I noticed this months ago but failed to find a minimal reproducible case, hopefully, #61 could help catch this. I'm not available recently to continue that but will do it eventually.

**Comment by juliohm** [comment]
Closing this as too old and due to the lack of a MWE.
